### ISSUE TITLE
Develop frontend image

### ISSUE THREAD

**Issue by giobart** [oakestra/dashboard#35]
Create a develop branch and add a GitHub workflow that builds develop FE images for testing purposes like this: 

Create alpha tags
https://github.com/oakestra/oakestra/blob/develop/.github/workflows/create-alpha-tags.yml

This creates an alpha tag from a push in develop triggering the new build

**Comment by TFphoenix** [comment]
Test comment

**Comment by TFphoenix** [comment]
Is the version.txt file generated manually? And if yes, which initial version should I use for the dashboard project?

**Comment by nitindermohan** [comment]
@TFphoenix While @giobart answers your dev-related first three points, let me answer your last one.
Yes, automated tests for frontend workflow would be highly appreciated. Could you possibly open a new issue with test requirements in `dashboard` repo? That ways we can have a more in-depth discussion, with inputs from @danimair9 as well.
