### ISSUE TITLE
Bug: new service creation fails due to missing application description

### ISSUE THREAD

**Issue by Malyuk-A** [oakestra/dashboard#37]
## Short
It is currently possible to create a new application without a description.
Adding new services to this application will throw errors because the BE expects to find a description for the application.

## Proposal 
In more detail:
~ 1 min long demo video that showcases this bug
https://github.com/oakestra/dashboard/assets/65814168/78b8afa8-a421-44de-b961-cd348fa99529

## Solution 
Either remove the BE requirement for applications to have a description,
or enforce it in the FE properly, so that it is no longer possible to create such an error-prone application.

## Status
I am looking for feedback. I would like to implement the solution myself but I would like to know if I should adjust the BE or FE.

## Checklist
- [x] Discussed
- [x] Solved
- [ ] Tested

**Comment by giobart** [comment]
I'd go for solution A: "Remove the BE requirement for applications to have a description"
It's pointless to force a description I guess. 

I'll move this issue to Oakestra repo since the scope is now the root orchestrator. Is that ok?
