### ISSUE TITLE
[Enhancment] Hide user password in create/edit new user

### ISSUE THREAD

**Issue by marinovl7** [oakestra/dashboard#40]
### Short
---
The password input field in create/edit user is currently not of type="password" and shows the text of the password. I personally think, that it is a good design decision to hide the password.

### Proposal
---
Make the input field of type="password" and add a icon/button to the most right of the container which will allow the user to toggle the written password.

### Ratio
---
I think this is a good UI/UX experience and proves the user, that the password is something secure.

### Impact
---
Only frontend

### Development time
---
~30 mins.

### Status
---
I want to develop this myself and will start right away

### Checklist
---
- [ ] Discussed
- [x] Implemented
- [ ] Tested

**Comment by nitindermohan** [comment]
@marinovl7 Thanks for the description. Did you already make progress on the issue? Should I assign this to you?

**Comment by giobart** [comment]
fixed in #41
